name: ContInt PullRequest
run-name: ContInt PullRequest

on: [pull_request, workflow_call]

jobs:
  Validate-in-ContInt-for-PullReq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Install ESlint
        run: npm run eslint

      - name: Run unit test
        run: npm run test

      - name: Install Browsers
        run: npx playwright install --with-deps

      - name: Run e2e test
        run: npm run e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 31

