name: deploy
on: workflow_dispatch
jobs:
    get_tag:
      runs-on: ubuntu-latest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 0
        - name: get last tag
          id: last
          run: |
            echo "TAG=$(git describe --tags --match v[0-9]* $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

        - name: checking tag
          id: ok
          run: echo ${{ steps.last.outputs.TAG }}


    perform-tests:
        needs: get_tag
        uses: ./.github/workflows/tests.yml
        with: 
          update_issue: true
          tagname: ${{ needs.get_tag.steps.last.outputs.TAG }}